package project.libraryclient.Consts;

public enum JsonType {
    NORMAL_LOGIN,
    GOOGLE_LOGIN,
    REGISTER_RESPONSE,
    LOGIN_RESPONSE,
    NORMAL_REGISTER,
    GOOGLE_REGISTER,
    RATING_BOOK,
    BORROW_BOOK,
    PENDING,
    BORROW_ACCEPTED,
    BORROW_DECLINED,
    BORROW_RECALL,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD_RESPONSE
}
